### ISSUE TITLE
KeyError totalChildrenCount after successful Send

### ISSUE THREAD

**Issue by sanzoghenzo** [specklesystems/speckle-qgis#21]
Hi there,

I think it's best if I file issues directly here instead of polluting the [forum discussion](https://speckle.community/t/qgis-connector-wip/1619/48)...

This is not a blocking error, but QGIS displays a warning after sending a layer to speckle:

```
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\speckle-qgis\speckle_qgis.py", line 370, in onReceiveButtonClicked
    traverseObject(commitObj, callback, check)
  File "C:\Users\andre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\speckle-qgis\speckle_qgis.py", line 66, in traverseObject
    traverseValue(base[name], callback, check)
  File "C:\Users\andre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\speckle-qgis\speckle_qgis.py", line 78, in traverseValue
    traverseValue(item, callback, check)
  File "C:\Users\andre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\speckle-qgis\speckle_qgis.py", line 75, in traverseValue
    traverseObject(value, callback, check)
  File "C:\Users\andre\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\speckle-qgis\speckle_qgis.py", line 66, in traverseObject
    traverseValue(base[name], callback, check)
  File "C:\Users\andre\AppData\Roaming\Python\Python39\site-packages\specklepy\objects\base.py", line 187, in __getitem__
    return self.__dict__[name]
KeyError: 'totalChildrenCount'
```

Data is correctly sent and I can receive it in a new QGIS project, though.

I don't know why the `onReceiveButtonClicked` method gets triggered.

QGIS 3.22.3 with python 3.9.5
speckle-qgis 0.1.1
specklepy 2.5.3

**Comment by sanzoghenzo** [comment]
Scratch this, I'm not able to reproduce it myself 😅 

I must have clicked the receive button by mistake!
